### ISSUE TITLE
consider backporting ITS#8324 to grow file incrementally on Windows

### ISSUE THREAD

**Issue by mykmelez** [mozilla/lmdb-rs#40]
Per [ITS#8324](http://www.openldap.org/its/index.cgi/Software%20Enhancements?id=8324), LMDB creates a database file at the map size on Windows rather than incrementally growing the file as on other platforms. The fix for that issue landed on the LMDB master branch several years ago, but it hasn't yet been backported to the release branch.

Note [this comment](https://github.com/lmdbjava/lmdbjava/issues/68#issuecomment-340473215) about why the fix wasn't backported. However, from cursory inspection, https://github.com/LMDB/lmdb/commit/e85ae1fe883b4847f07cfebc2630636d06e429c3 might have since addressed that problem.

In any case, since the fix for ITS#8324 hasn't landed upstream, and since it impacts lmdb-rs consumers (per #23), we should consider taking it downstream. That would mean taking not only the original commit but also its follow-ups. This list of [commits containing the string "ITS#8324"](https://github.com/LMDB/lmdb/search?q=%22ITS%238324%22&type=Commits&utf8=%E2%9C%93) is presumably the set we would need to backport.

**Comment by mykmelez** [comment]
This email message explains in more detail why the fix wasn't backported. Based on that explanation, it seems like a bad idea for us to do so:

http://www.openldap.org/lists/openldap-bugs/201902/msg00009.html

**Comment by iainnicol** [comment]
FWIW, I encountered this running MeiliSearch on Windows.

I see from your link there's an unfortunate trade off for enabling this feature, in terms of performance.  What is new is that this is now compile-term optional (in upstream lmdb): https://github.com/LMDB/lmdb/commit/147582b5dcd86d1d92bb9a3fda9eb640300ccae3

So that's good. But I presume, understandably, the intention would be to wait until LMDB v1.0, before considering merging such code.
