### ISSUE TITLE
Set write flags on trx or for each put?

### ISSUE THREAD

**Issue by dvdplm** [mozilla/lmdb-rs#47]
I am a little confused by [this line](https://github.com/mozilla/lmdb-rs/blob/master/src/transaction.rs#L236) that passes an empty `EnvironmentFlags` to `ffi::mdb_txn_begin`. Should it be a `WriteFlags::empty()`?

That brings another question/doubt: it seems logical to me to set any write flags on the transactions and have all write operations within the transaction use the same `WriteFlags`, but the way the code works atm `RwTransaction::new()` hardcodes an empty flag byte and the only place to set the write flag is in `put`/`reserve`. Should it perhaps be the other way around, i.e. set the write flags when creating the transactions and use that for all writes?

**Comment by mykmelez** [comment]
> I am a little confused by [this line](https://github.com/mozilla/lmdb-rs/blob/master/src/transaction.rs#L236) that passes an empty `EnvironmentFlags` to `ffi::mdb_txn_begin`. Should it be a `WriteFlags::empty()`?

[mdb_txn_begin()](http://www.lmdb.tech/doc/group__mdb.html#gad7ea55da06b77513609efebd44b26920) takes a `flags` argument that only respects a single flag, [MDB_RDONLY](http://www.lmdb.tech/doc/group__mdb__env.html#gac4c41c0ae044127b2fc80420c323cac6), which it shares with the `flags` parameter to [mdb_env_open()](http://www.lmdb.tech/doc/group__mdb.html#ga32a193c6bf4d7d5c5d579e71f22e9340). This Rust wrapper then reflects that flag into the `EnvironmentFlags` struct as the `EnvironmentFlags::READ_ONLY` const.

That achieves [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) but at the cost of some confusion. To reduce confusion, we could create a `TransactionFlags` struct with a `TransactionFlags::READ_ONLY` const (set to the same value as the equivalent const in `EnvironmentFlags`, natch). Then `RwTransaction::new()` could pass a `TransactionFlags::empty().bits()` to `mdb_txn_begin()`.

> That brings another question/doubt: it seems logical to me to set any write flags on the transactions and have all write operations within the transaction use the same `WriteFlags`, but the way the code works atm `RwTransaction::new()` hardcodes an empty flag byte and the only place to set the write flag is in `put`/`reserve`. Should it perhaps be the other way around, i.e. set the write flags when creating the transactions and use that for all writes?

In the underlying storage engine (LMDB), [Write Flags](http://www.lmdb.tech/doc/group__mdb__put.html) are specific to individual changes (i.e. `mdb_put()`, `mdb_cursor_put()`, `mdb_cursor_del()`, and perhaps others), not to the write transaction as a whole. The `WriteFlags` struct in this Rust wrapper just reflects that underlying API.

We could nevertheless allow consumers to set write flags when creating a transaction and then automatically apply those flags to all writes in that transaction, so consumers don't have to apply the flags to each individual write.

However, it isn't clear to me how common it is to share write flags within a transaction. The `APPEND` flag might be shared most of the time, since if you're doing "fast bulk loading," then your transaction will presumably be a set of `RwTransaction.put()` calls, all of which will have the `APPEND` flag set. But I'm less sure about the others.

And this Rust wrapper is mostly a thin wrapper over the underlying LMDB APIs, with only enough abstraction to improve safety (and in some cases clarity, such as the reflection of prefixed and abbreviated LMDB flags like `MDB_RDONLY` into structured and spelled-out flags like `EnvironmentFlags::READ_ONLY`).

Thus my inclination is to be conservative about the way we reflect the underlying APIs into Rust APIs in this crate. However, for the [rkv](https://github.com/mozilla/rkv) crate, which wraps this wrapper in higher-level abstractions, I'm more sanguine about changing the way we reflect the underlying APIs.

**Comment by dvdplm** [comment]
> The APPEND flag might be shared most of the time, since if you're doing "fast bulk loading," then your transaction will presumably be a set of RwTransaction.put() calls, all of which will have the APPEND flag set.

This is indeed my use case. And I agree: other than `APPEND` it's probably not common to want to apply the flag to all operations in a transaction.

> inclination is to be conservative about the way we reflect the underlying APIs into Rust APIs in this crate. 

Makes sense, and again I agree that this is probably best handled at a higher-level.

Thank you for taking the time to explain, much appreciated. :)
